### ISSUE TITLE
how to display pinned on Instagram comments

### ISSUE THREAD

**Issue by penteseter123** [subins2000/InstaLV#1]
how to display pinned on Instagram comments with php live programs thanks help me for coding and develop 
![image](https://user-images.githubusercontent.com/35046129/44000646-2aa6c704-9e4e-11e8-8cd0-0a9a7fbd38fa.png)

**Comment by penteseter123** [comment]
can it develop with coding Jroy for Localhost 
https://github.com/JRoy/InstagramLive-PHP/releases/tag/0.5-BETA-3

**Comment by subins2000** [comment]
I'm working on it

**Comment by subins2000** [comment]
[v0.2](https://github.com/subins2000/InstaLV/releases/tag/v0.2)

**Comment by penteseter123** [comment]
This code only releases version 0.2 for pins and unpin just can't add
comments. Developer Jroy has added code for how we can respond to comments
from other audiences and coding that has been developed by Jroy, please add
it and can be enjoyed on Localhost
https://github.com/JRoy/InstagramLive-PHP/find/80c01119d74e1e323152e353df4ea9d15a8d4b6d
https://drive.google.com/open?id=11s0Ezf4iJEEOiYzK3HeznPb7FkszVMes
can you develop it for the addition to responding to the audience from the
comments thank you for waiting and I want to test it
![screenshot_59](
https://user-images.githubusercontent.com/35046129/44612499-36bdb180-a833-11e8-9e54-536c4b25734b.png
)
[image: Screenshot_59.png]
